-- Creating my first table

CREATE TABLE TB_CLIENTES
    (CPF CHAR(11),NOME VARCHAR(100), ENDERECO1 VARCHAR(150), ENDERECO2 VARCHAR(150), BAIRRO VARCHAR(50), CIDADE VARCHAR(150),
    CEP CHAR(8), IDADE INT, SEXO VARCHAR(1), LIMITE_CREDITO FLOAT, VOLUME_COMPRA FLOAT, PRIMEIRA_COMPRA NUMBER(1));
