-- Recover Dropped Tables using Flashback

CREATE TABLE HOUDINI (VOILA VARCHAR2(30));

INSERT INTO HOUDINI (VOILA) VALUES ('Now you see it.');
COMMIT;

DROP TABLE HOUDINI;

FLASHBACK TABLE HOUDINI TO BEFORE DROP;

SELECT * FROM HOUDINI;

SHOW RECYCLEBIN;

SELECT OBJECT_NAME, ORIGINAL_NAME, TYPE, DROPTIME FROM USER_RECYCLEBIN;

ALTER SESSION SET recyclebin = ON;

ALTER SYSTEM SET recyclebin = ON;

ALTER SYSTEM SET recyclebin = ON SCOPE = SPFILE;

SELECT * FROM RECYCLEBIN;

CREATE TABLE HOUDINI (VOILA VARCHAR2(30));

INSERT INTO HOUDINI (VOILA) VALUES ('Now you see it');
COMMIT;
EXECUTE DBMS_LOCK.SLEEP(15);
DELETE FROM HOUDINI;
COMMIT;
EXECUTE DBMS_LOCK.SLEEP(15);
FLASHBACK TABLE HOUDINI TO TIMESTAMP SYSTIMESTAMP - INTERVAL '0 00:00:20' DAY TO SECOND;

ALTER TABLE HOUDINI ENABLE ROW MOVEMENT;

SHOW PARAMETER recyclebin;

DROP TABLE houdini PURGE;

SELECT tablespace_name, flashback_on FROM dba_tablespaces;

