-- EXISTS

SELECT PORT_ID, PORT_NAME FROM PORTS P1
    WHERE EXISTS
    (SELECT * FROM SHIPS S1 WHERE P1.PORT_ID = S1.HOME_PORT_ID);
    
-- WITH CLAUSE

WITH
    PORT_BOOKINGS AS (
    SELECT P.PORT_ID, P.PORT_NAME, COUNT(S.SHIP_ID) CT
    FROM PORTS P, SHIPS S
    WHERE P.PORT_ID = S.HOME_PORT_ID
    GROUP BY P.PORT_ID, P.PORT_NAME
    ),
    DENSERT_PORT AS (
    SELECT MAX(CT) MAX_CT
    FROM PORT_BOOKINGS
    )
    SELECT PORT_NAME
    FROM PORT_BOOKINGS 
    WHERE CT = (SELECT MAX_CT FROM DENSERT_PORT);
    
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
    ADD (
    SSN VARCHAR2(11),
    DOB DATE,
    PRIMARY_PHONE VARCHAR2(20));
    
UPDATE EMPLOYEES
SET SSN = CASE EMPLOYEE_ID
             WHEN 1 THEN '123-45-6789'
             WHEN 2 THEN '987-65-4321'
             WHEN 3 THEN '111-22-3333'
             WHEN 4 THEN '444-55-6666'
             WHEN 5 THEN '777-88-9999'
             WHEN 6 THEN '000-12-3456'
             WHEN 7 THEN '543-21-0987'
          END,
    DOB = CASE EMPLOYEE_ID
             WHEN 1 THEN TO_DATE('01-01-1980', 'DD-MM-YYYY')
             WHEN 2 THEN TO_DATE('02-02-1981', 'DD-MM-YYYY')
             WHEN 3 THEN TO_DATE('03-03-1982', 'DD-MM-YYYY')
             WHEN 4 THEN TO_DATE('04-04-1983', 'DD-MM-YYYY')
             WHEN 5 THEN TO_DATE('05-05-1984', 'DD-MM-YYYY')
             WHEN 6 THEN TO_DATE('06-06-1985', 'DD-MM-YYYY')
             WHEN 7 THEN TO_DATE('07-07-1986', 'DD-MM-YYYY')
          END,
    primary_phone = CASE EMPLOYEE_ID
             WHEN 1 THEN '1111-1111'
             WHEN 2 THEN '2222-2222'
             WHEN 3 THEN '3333-3333'
             WHEN 4 THEN '4444-4444'
             WHEN 5 THEN '5555-5555'
             WHEN 6 THEN '6666-6666'
             WHEN 7 THEN '7777-7777'
          END;

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID FROM EMPLOYEES
    WHERE LAST_NAME = 'Smith' AND FIRST_NAME = 'Jane';
    
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME FROM EMPLOYEES
    WHERE SALARY > 7000
    AND NOT (LAST_NAME = 'Smith' AND FIRST_NAME = 'Jane');

SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME
    FROM EMPLOYEES
        WHERE SHIP_ID = (SELECT SHIP_ID FROM EMPLOYEES WHERE LAST_NAME = 'Smith'
        AND FIRST_NAME = 'Al') AND NOT (LAST_NAME = 'Smith' AND FIRST_NAME = 'A1');
        


    