-- INNER JOIN

SELECT * FROM CLIENTES;

SELECT * FROM PEDIDOS;

SELECT C.ID_CLIENTE, P.ID_PEDIDO, C.NOME_CLIENTE FROM CLIENTES C
    JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_CLIENTE
    WHERE C.NOME_CLIENTE = 'Alice';

SELECT C.ID_CLIENTE, P.ID_PEDIDO, C.NOME_CLIENTE
    FROM CLIENTES C
    JOIN PEDIDOS P
        ON C.ID_CLIENTE = P.ID_CLIENTE
        WHERE C.NOME_CLIENTE LIKE 'Alice';
        
-- Natural Join
SELECT  ID_CLIENTE, ID_PEDIDO, NOME_CLIENTE FROM CLIENTES C
    NATURAL JOIN PEDIDOS P;

SELECT ID_CLIENTE, ID_PEDIDO, NOME_CLIENTE FROM CLIENTES
    NATURAL LEFT OUTER JOIN PEDIDOS;
    
SELECT ID_CLIENTE, ID_PEDIDO, NOME_CLIENTE FROM CLIENTES
    NATURAL RIGHT OUTER JOIN PEDIDOS;

SELECT ID_CLIENTE, ID_PEDIDO, NOME_CLIENTE FROM CLIENTES
    NATURAL FULL OUTER JOIN PEDIDOS;

-- Using
SELECT ID_CLIENTE, ID_PEDIDO, NOME_CLIENTE FROM CLIENTES
    LEFT JOIN PEDIDOS
    USING (ID_CLIENTE);
    
-- non-equijoin
SELECT E.nome, F.descricao
FROM Empregados E
JOIN FaixasSalarial F
  ON E.salario BETWEEN F.faixa_min AND F.faixa_max;
  
-- Self join
SELECT f.nome AS funcionario, s.nome AS supervisor
FROM Funcionarios f
LEFT JOIN Funcionarios s
  ON f.supervisor_id = s.id;
  
SELECT C.ID_CLIENTE, P.ID_PEDIDO, C.NOME_CLIENTE FROM CLIENTES C
    LEFT OUTER JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_CLIENTE;
    
SELECT C.ID_CLIENTE, P.ID_PEDIDO, C.NOME_CLIENTE FROM CLIENTES C
    RIGHT OUTER JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_CLIENTE;
