-- 

SELECT DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER FROM DUAL;

SELECT * FROM SHIPS;

SELECT ORA_ROWSCN, SHIP_NAME FROM SHIPS;

SELECT TO_TIMESTAMP('2017-08-25 13:15:08.232349', 'RRRR-MM-DD HH24:MI:SS:FF')
    FROM DUAL;
    

SELECT TIMESTAMP_TO_SCN(SYSTIMESTAMP) NOW,
    TIMESTAMP_TO_SCN(TO_TIMESTAMP('01-AGO-09 09:12:23', 'DD-MON-RR HH:MI:SS'))
    NOT_NOW FROM DUAL;