CREATE TABLE SEMINARS
    (SEMINAR_ID NUMBER(11) PRIMARY KEY,
    SEMINAR_NAME VARCHAR(30) UNIQUE);

SELECT TABLE_NAME, INDEX_NAME FROM USER_INDEXES
    WHERE TABLE_NAME = 'SEMINARS';
    
SELECT INDEX_NAME, COLUMN_NAME FROM USER_IND_COLUMNS
    WHERE TABLE_NAME = 'SEMINARS';

CREATE INDEX IX_INV_INVOICE_DATE ON INVOICES(INVOICE_DATE);

SELECT * FROM INVOICES WHERE INVOICE_DATE = '14-FEB-2017';