-- First, Last
-- Syntax: Agreggate_function KEEP (DENSE_RANK FIRST ORDER BY e1)
--         Agreggate_function KEEP (DENSE_RANK LAST ORDER BY e1)

SELECT MAX(SQ_FT) KEEP (DENSE_RANK FIRST ORDER BY GUESTS) AS LARGEST
FROM SHIP_CABINS;

-- GROUP BY
SELECT ROUND(AVG(SALARY), 2) FROM EMPLOYEES WHERE EMPLOYEE_ID = 1;

SELECT ROUND(AVG(SALARY), 2) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY), 2) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2) FROM EMPLOYEES WHERE SALARY BETWEEN 1000 AND 20000
    GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;
    
SELECT DEPARTMENT_ID, TO_CHAR(MIN(SALARY), '9,999') AS "MIN",
    TO_CHAR(MAX(SALARY), '9,999') AS "MAX",
    TO_CHAR(MIN(SALARY) - MAX(SALARY), '9,999') "DIFF"
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID ORDER BY 2;


SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY department_id

