-- Sequences

CREATE SEQUENCE SEQ_ORDER_ID;

-- Complete syntax

CREATE SEQUENCE sequence_name sequence_options;

DROP SEQUENCE SEQ_ORDER_ID;

CREATE SEQUENCE SEQ_ORDER_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ORDER_ID START WITH 10 INCREMENT BY 5;

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, CUSTOMER_ID)
    VALUES (SEQ_ORDER_ID.NEXTVAL, SYSDATE, 28)

SELECT SEQ_ORDER_ID.NEXTVAL FROM DUAL;

SELECT SEQ_ORDER_ID.NEXTVAL FROM DUAL;