-- EXPLAIN PLAN
SELECT * FROM EMPLOYEES;

EXPLAIN PLAN FOR
    SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;
    
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- COMPOSITE

CREATE INDEX IX_INV_INVOICE_VENDOR_ID ON INVOICES(VENDOR_ID, INVOICE_DATE);

SELECT * FROM INVOICES WHERE VENDOR_ID = 10 AND INVOICE_DATE = SYSDATE;

SELECT * FROM INVOICES WHERE VENDOR_ID = 10;

-- Unique

SELECT UNIQUE INDEX IX_EMP_SSN ON EMPLOYEES;

CREATE UNIQUE INDEX IX_FUNC_DEP_NUM ON FUNCIONARIOS (ID_DEPARTAMENTO, NUMERO_FUNCIONAL);

CREATE INDEX IX_PEDIDOS_DATA ON PEDIDOS (DATA_PEDIDO);

CREATE BITMAP INDEX IX_PROD_CAT ON PRODUTOS (CATEGORIA_PRODUTO);

CREATE INDEX IX_CLIENTE_NOME_UPPER ON CLIENTES (UPPER(NOME_CLIENTE));

CREATE INDEX IX_LOGS_DATA_DESC ON LOGS (DATA_EVENTO DESC);

CREATE UNIQUE INDEX IX_EMP_SSN ON EMPLOYEES(SSN);

CREATE INDEX IX_VENDAS_VALOR ON VENDAS (VALOR_VENDA) LOCAL;

DROP INDEX IX_INV_INVOICE_DATE;