-- Count
-- Syntax: COUNT(e1)

DESC employees;

SELECT DEPARTMENT_ID, COUNT(*) AS EMPLOYEE_COUNT
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID;
    
SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY)
    VALUES (7, 'Kevin', 'De Bruyne', 30, 18000)
    
SELECT COUNT(FIRST_NAME), COUNT(LAST_NAME), COUNT(DEPARTMENT_ID) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES;

SELECT COUNT(*), COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(ALL LAST_NAME), COUNT(DISTINCT DEPARTMENT_ID) FROM EMPLOYEES;
