-- Functions in SQL

SELECT * FROM estudantes;

SELECT NOME, INITCAP(NOME) FROM ESTUDANTES;

SELECT SYSDATE FROM DUAL;

SELECT NOME FROM ESTUDANTES WHERE UPPER(NOME) = 'MARIA GARCIA';

-- Author Joamir