-- Functions in SQL

SELECT * FROM estudantes;

SELECT NOME, INITCAP(NOME) FROM ESTUDANTES;

SELECT SYSDATE FROM DUAL;

SELECT NOME FROM ESTUDANTES WHERE UPPER(NOME) = 'MARIA GARCIA';

SELECT NOME FROM ESTUDANTES WHERE LOWER(NOME) = 'maria garcia';

SELECT INITCAP('napoleon'), INITCAP('RED O''BRIEN'), INITCAP('McDonald''s')
    FROM DUAL;
