SELECT * FROM CRUISES;

SELECT * FROM CRUISES ORDER BY CRUISE_NAME, CAPTAIN_ID;

SELECT * FROM CRUISES ORDER BY CRUISE_NAME asc , CAPTAIN_ID;

SELECT CRUISE_ID CRUISE_DI, CRUISE_NAME NAME_CRUISE FROM CRUISES CR
    ORDER BY CRUISE_DI DESC;
    
SELECT CRUISE_ID "CRUISE_DI", CRUISE_NAME NAME_CRUISE FROM CRUISES CR
    ORDER BY CRUISE_DI DESC;
    
SELECT CRUISE_ID CRUISE_IDENT, CRUISE_NAME FROM CRUISES
    ORDER BY CRUISE_IDENT DESC,  2;
    
    