-- Update rows

UPDATE CRUISES SET CRUISE_NAME = 'Bahamas', START_DATE = '01-DEZ-11'
    WHERE CRUISE_ID = 1;

CREATE TABLE COMPENSATION
    (ID_EMPLOYEE NUMBER PRIMARY KEY,
    SALARY NUMBER(10, 2) NOT NULL,
    LAST_CHANGED_DATE DATE
    );

INSERT INTO COMPENSATION (id_employee, salary, last_changed_date)
    VALUES (205, 10000, '15-OUT-2018');
    
UPDATE COMPENSATION SET SALARY = SALARY * 1.03, LAST_CHANGED_DATE = SYSDATE
    WHERE ID_EMPLOYEE = 205;

SELECT
    A.ID_EMPLOYEE,
    A.SALARY,
    A.LAST_CHANGED_DATE
FROM
    SYS.COMPENSATION A;
    
