CREATE DIRECTORY INVOICE_FILE AS '\LOAD_INVOICES';

CREATE TABLE INVOICE_EXTERNAL (
    INVOICE_ID CHAR(3),
    INVOICE_DATE CHAR(9),
    ACCOUNT_NUMBER CHAR(13)
    )
ORGANIZATION EXTERNAL
    (TYPE ORACLE_LOADER
    DEFAULT DIRECTORY INVOICE_FILE
    ACCESS PARAMETERS
        (RECORDS DELIMITED BY NEWLINE
        SKIP 2
        FIELDS (INVOICE_ID CHAR(3),
                INVOICE_DATE CHAR(9),
                ACCOUNT_NUMBER CHAR(13))
    )
    LOCATION ('INVOICE_DATA.TXT')
    );

SELECT * FROM INVOICE_EXTERNAL;