CREATE TABLE PORTS (
    PORT_ID NUMBER PRIMARY KEY,
    PORT_NAME VARCHAR2 (20));


ALTER TABLE PORTS
    ADD 
        ( STATUS NUMBER(1),
          CATEGORY_PORT VARCHAR2(5)
);

SELECT * FROM PORTS;

CREATE TABLE VENDORS (
    VENDOR_ID NUMBER,
    VENDOR_NAME VARCHAR2(20),
    STATUS NUMBER(1) CONSTRAINT STATUS_NN NOT NULL,
    CATEGORY_VENDOR VARCHAR2(5));
    
    
ALTER TABLE VENDORS
MODIFY VENDOR_ID PRIMARY KEY;

CREATE TABLE VENDORS
    ( VENDOR_ID NUMBER,
    VENDOR_NAME VARCHAR2(30),
    CATEGORY CHAR);
    
ALTER TABLE PORTS SET UNUSED COLUMN PORT_NAME;

TRUNCATE TABLE PORTS;