COMMIT;

INSERT INTO PORTS VALUES (
    13, 'Itaqui', 'BR', 12000, 'Maranhão');

INSERT INTO PORTS (PORT_ID, PORT_NAME, COUNTRY, CAPACITY) 
VALUES (
    12, 'Galinhas', 'BR', 14000);
    
INSERT INTO PORTS (PORT_ID, PORT_NAME, COUNTRY, CAPACITY) 
VALUES (
    21, 'Dunas', 'BR', 10000);
    
INSERT INTO PORTS (PORT_ID, PORT_NAME, COUNTRY, CAPACITY) 
VALUES (
    21, 'Balsas', 'BR', 11000);
    
DESC PORTS;
DESC SHIPS;

INSERT INTO SHIPS ( SHIP_ID, SHIP_NAME, HOME_PORT_ID)
    VALUES
    (12, 'Guimarães', 13);
    
INSERT INTO SHIPS ( SHIP_ID, SHIP_NAME, HOME_PORT_ID)
    VALUES
    (14, 'São Luís', 15);

UPDATE SHIPS SET HOME_PORT_ID = 21 WHERE SHIP_ID =14;

SAVEPOINT SP_1;

UPDATE SHIPS SET HOME_PORT_ID = 22 WHERE SHIP_ID = 12;

ROLLBACK WORK TO SP_1;

COMMIT;