CREATE TABLE PORTS (
    PORT_ID NUMBER,
    PORT_NAME VARCHAR2(20),
    COUNTRY VARCHAR2(40),
    CAPACITY NUMBER,
    CONSTRAINT PORT_PK PRIMARY KEY (PORT_ID));
    
CREATE TABLE SHIPS (
    SHIP_ID NUMBER,
    SHIP_NAME VARCHAR2(20),
    HOME_PORT_ID NUMBER,
    CONSTRAINT SHIPS_PORTS_FK FOREIGN KEY (HOME_PORT_ID) REFERENCES
        PORTS (PORT_ID) ON DELETE CASCADE);
        
        
INSERT INTO PORTS VALUES (315, 'Atlanta', 'USA', 1000);
INSERT INTO SHIPS VALUES (4000, 'Codd Land Rover', 315);
INSERT INTO SHIPS VALUES (4001, 'Codd Vessel Two', NULL);


-- Deleting previous table
DESC PORTS

ALTER TABLE PORTS DROP COLUMN PORT_ID CASCADE CONSTRAINTS;

DROP TABLE PORTS CASCADE CONSTRAINTS;

DROP TABLE SHIPS CASCADE CONSTRAINTS;

TRUNCATE TABLE PORTS;

TRUNCATE TABLE SHIPS;

TRUNCATE TABLE PORTS CASCADE;
