SELECT * FROM CRUISES;

SELECT CRUISE_NAME, CAPTAIN_ID, START_DATE
    FROM CRUISES
    WHERE CRUISE_NAME = '&CRUISE'
    ORDER BY CAPTAIN_ID;
    
SELECT CRUISE_NAME, CAPTAIN_ID, START_DATE
    FROM CRUISES
    WHERE CAPTAIN_ID = &ID_CAPTAIN;
    
SELECT &Column_choice
    FROM CRUISES;
