CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

DELETE FROM ITEMS_NOTAS;
DELETE FROM NOTAS;

SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS
TOTAL_VENDA FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;

CREATE TRIGGER TG_CALCULO_FATURAMENTO
AFTER INSERT OR UPDATE OR DELETE ON ITEMS_NOTAS
BEGIN

DELETE FROM ITEMS_NOTAS;

DELETE FROM NOTAS;

SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS
TOTAL_VENDA FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;

END;